In [42]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [43]:
%pprint

#This line makes sure that matplotlib prints the plots
%matplotlib inline

# This just sets the default plot size to be bigger.
plt.rcParams['figure.figsize'] = (16, 12)

Pretty printing has been turned OFF

To get up to date and trusted data I have gone to the website of the European Centre for Disease Prevention and Control which is an agency for the European Union. The website link is below. 

(When I have the notebook finished, I will try to pull the data directly from the website)

https://www.ecdc.europa.eu/en/publications-data/download-todays-data-geographic-distribution-covid-19-cases-worldwide

In [44]:
# reading in a csv file from ecdc website download, for up to date data
df = pd.read_csv("COVID-19Cases_05.07.2020.csv")
df

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp
0,05/07/2020,5,7,2020,348,7,Afghanistan,AF,AFG,38041757.0,Asia
1,04/07/2020,4,7,2020,302,12,Afghanistan,AF,AFG,38041757.0,Asia
2,03/07/2020,3,7,2020,186,33,Afghanistan,AF,AFG,38041757.0,Asia
3,02/07/2020,2,7,2020,319,28,Afghanistan,AF,AFG,38041757.0,Asia
4,01/07/2020,1,7,2020,279,13,Afghanistan,AF,AFG,38041757.0,Asia
...,...,...,...,...,...,...,...,...,...,...,...
27826,25/03/2020,25,3,2020,0,0,Zimbabwe,ZW,ZWE,14645473.0,Africa
27827,24/03/2020,24,3,2020,0,1,Zimbabwe,ZW,ZWE,14645473.0,Africa
27828,23/03/2020,23,3,2020,0,0,Zimbabwe,ZW,ZWE,14645473.0,Africa
27829,22/03/2020,22,3,2020,1,0,Zimbabwe,ZW,ZWE,14645473.0,Africa
27830,21/03/2020,21,3,2020,1,0,Zimbabwe,ZW,ZWE,14645473.0,Africa

In [45]:
# information on number of pieces of data in columns and datatype
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27831 entries, 0 to 27830
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   dateRep                  27831 non-null  object
 1   day                      27831 non-null  int64
 2   month                    27831 non-null  int64
 3   year                     27831 non-null  int64
 4   cases                    27831 non-null  int64
 5   deaths                   27831 non-null  int64
 6   countriesAndTerritories  27831 non-null  object
 7   geoId                    27718 non-null  object
 8   countryterritoryCode     27767 non-null  object
 9   popData2019              27767 non-null  float64
 10  continentExp             27831 non-null  object
dtypes: float64(1), int64(5), object(5)
memory usage: 2.3+ MB

As you can see above the date column is not a date datatype, I will need to change that so that data stays in order.

In [46]:
#using pandas built in to_datetime function to change the dateRep column form object to a datetime object
df['dateRep'] = pd.to_datetime(df['dateRep'], format='%d/%m/%Y')
df

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp
0,2020-07-05,5,7,2020,348,7,Afghanistan,AF,AFG,38041757.0,Asia
1,2020-07-04,4,7,2020,302,12,Afghanistan,AF,AFG,38041757.0,Asia
2,2020-07-03,3,7,2020,186,33,Afghanistan,AF,AFG,38041757.0,Asia
3,2020-07-02,2,7,2020,319,28,Afghanistan,AF,AFG,38041757.0,Asia
4,2020-07-01,1,7,2020,279,13,Afghanistan,AF,AFG,38041757.0,Asia
...,...,...,...,...,...,...,...,...,...,...,...
27826,2020-03-25,25,3,2020,0,0,Zimbabwe,ZW,ZWE,14645473.0,Africa
27827,2020-03-24,24,3,2020,0,1,Zimbabwe,ZW,ZWE,14645473.0,Africa
27828,2020-03-23,23,3,2020,0,0,Zimbabwe,ZW,ZWE,14645473.0,Africa
27829,2020-03-22,22,3,2020,1,0,Zimbabwe,ZW,ZWE,14645473.0,Africa
27830,2020-03-21,21,3,2020,1,0,Zimbabwe,ZW,ZWE,14645473.0,Africa

In [47]:
#checking info to see the datatype of dataRep now
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27831 entries, 0 to 27830
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   dateRep                  27831 non-null  datetime64[ns]
 1   day                      27831 non-null  int64
 2   month                    27831 non-null  int64
 3   year                     27831 non-null  int64
 4   cases                    27831 non-null  int64
 5   deaths                   27831 non-null  int64
 6   countriesAndTerritories  27831 non-null  object
 7   geoId                    27718 non-null  object
 8   countryterritoryCode     27767 non-null  object
 9   popData2019              27767 non-null  float64
 10  continentExp             27831 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(5), object(4)
memory usage: 2.3+ MB

In [48]:
# a quick look at the head of the data to see how many columns we have and if we can get rid of some that are not needed
df.head()

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp
0,2020-07-05,5,7,2020,348,7,Afghanistan,AF,AFG,38041757.0,Asia
1,2020-07-04,4,7,2020,302,12,Afghanistan,AF,AFG,38041757.0,Asia
2,2020-07-03,3,7,2020,186,33,Afghanistan,AF,AFG,38041757.0,Asia
3,2020-07-02,2,7,2020,319,28,Afghanistan,AF,AFG,38041757.0,Asia
4,2020-07-01,1,7,2020,279,13,Afghanistan,AF,AFG,38041757.0,Asia

In [49]:
# Statistical description of the data
df.describe()

,day,month,year,cases,deaths,popData2019
count,27831.000000,27831.000000,27831.000000,27831.000000,27831.000000,2.776700e+04
mean,15.814811,4.312996,2019.997593,403.925658,19.067515,4.640626e+07
std,8.994855,1.617419,0.049007,2351.306962,120.833161,1.664285e+08
min,1.000000,1.000000,2019.000000,-29726.000000,-1918.000000,8.150000e+02
25%,8.000000,3.000000,2020.000000,0.000000,0.000000,1.798506e+06
50%,16.000000,4.000000,2020.000000,4.000000,0.000000,8.776119e+06
75%,24.000000,6.000000,2020.000000,72.000000,1.000000,3.182530e+07
max,31.000000,12.000000,2020.000000,54771.000000,4928.000000,1.433784e+09

In [50]:
# shape of the data is (rows, columns)
df.shape

(27831, 11)

In [51]:
# column headers
df.keys()

Index(['dateRep', 'day', 'month', 'year', 'cases', 'deaths',
       'countriesAndTerritories', 'geoId', 'countryterritoryCode',
       'popData2019', 'continentExp'],
      dtype='object')

In [52]:
# we will drop the columns we do not need
reduced_columns = df.drop(['day', 'month', 'year','geoId', 'countryterritoryCode', 'continentExp'], axis=1)

In [53]:
# head of our new slimed down dataframe
reduced_columns.head()

     dateRep  cases  deaths countriesAndTerritories  popData2019
0 2020-07-05    348       7             Afghanistan   38041757.0
1 2020-07-04    302      12             Afghanistan   38041757.0
2 2020-07-03    186      33             Afghanistan   38041757.0
3 2020-07-02    319      28             Afghanistan   38041757.0
4 2020-07-01    279      13             Afghanistan   38041757.0

In [54]:
# final 5 columns
reduced_columns.tail()

         dateRep  cases  deaths countriesAndTerritories  popData2019
27826 2020-03-25      0       0                Zimbabwe   14645473.0
27827 2020-03-24      0       1                Zimbabwe   14645473.0
27828 2020-03-23      0       0                Zimbabwe   14645473.0
27829 2020-03-22      1       0                Zimbabwe   14645473.0
27830 2020-03-21      1       0                Zimbabwe   14645473.0

In [55]:
# we will now drop the deaths column
reduced_columns_cases = reduced_columns.drop(['deaths'], axis=1)
reduced_columns_cases.head()

     dateRep  cases countriesAndTerritories  popData2019
0 2020-07-05    348             Afghanistan   38041757.0
1 2020-07-04    302             Afghanistan   38041757.0
2 2020-07-03    186             Afghanistan   38041757.0
3 2020-07-02    319             Afghanistan   38041757.0
4 2020-07-01    279             Afghanistan   38041757.0

In [56]:
reduced_columns_cases['casesPer100KPop'] = reduced_columns_cases.cases * 100000 / reduced_columns_cases.popData2019
reduced_columns_cases

         dateRep  cases countriesAndTerritories  popData2019  casesPer100KPop
0     2020-07-05    348             Afghanistan   38041757.0         0.914784
1     2020-07-04    302             Afghanistan   38041757.0         0.793864
2     2020-07-03    186             Afghanistan   38041757.0         0.488936
3     2020-07-02    319             Afghanistan   38041757.0         0.838552
4     2020-07-01    279             Afghanistan   38041757.0         0.733405
...          ...    ...                     ...          ...              ...
27826 2020-03-25      0                Zimbabwe   14645473.0         0.000000
27827 2020-03-24      0                Zimbabwe   14645473.0         0.000000
27828 2020-03-23      0                Zimbabwe   14645473.0         0.000000
27829 2020-03-22      1                Zimbabwe   14645473.0         0.006828
27830 2020-03-21      1                Zimbabwe   14645473.0         0.006828

[27831 rows x 5 columns]

In [57]:
reduced_columns_cases.set_index('dateRep')

            cases countriesAndTerritories  popData2019  casesPer100KPop
dateRep
2020-07-05    348             Afghanistan   38041757.0         0.914784
2020-07-04    302             Afghanistan   38041757.0         0.793864
2020-07-03    186             Afghanistan   38041757.0         0.488936
2020-07-02    319             Afghanistan   38041757.0         0.838552
2020-07-01    279             Afghanistan   38041757.0         0.733405
...           ...                     ...          ...              ...
2020-03-25      0                Zimbabwe   14645473.0         0.000000
2020-03-24      0                Zimbabwe   14645473.0         0.000000
2020-03-23      0                Zimbabwe   14645473.0         0.000000
2020-03-22      1                Zimbabwe   14645473.0         0.006828
2020-03-21      1                Zimbabwe   14645473.0         0.006828

[27831 rows x 4 columns]

In [62]:
cases = reduced_columns_cases.pivot(index='dateRep', columns='countriesAndTerritories', values='casesPer100KPop')
cases.head()

countriesAndTerritories,Afghanistan,Albania,Algeria,Andorra,Angola,Anguilla,Antigua_and_Barbuda,Argentina,Armenia,Aruba,...,United_States_Virgin_Islands,United_States_of_America,Uruguay,Uzbekistan,Venezuela,Vietnam,Western_Sahara,Yemen,Zambia,Zimbabwe
dateRep,,,,,,,,,,,,,,,,,,,,,
2019-12-31,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
2020-01-01,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
2020-01-02,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
2020-01-03,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
2020-01-04,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN

In [63]:
cases.fillna(0, inplace=True)
cases

countriesAndTerritories,Afghanistan,Albania,Algeria,Andorra,Angola,Anguilla,Antigua_and_Barbuda,Argentina,Armenia,Aruba,...,United_States_Virgin_Islands,United_States_of_America,Uruguay,Uzbekistan,Venezuela,Vietnam,Western_Sahara,Yemen,Zambia,Zimbabwe
dateRep,,,,,,,,,,,,,,,,,,,,,
2019-12-31,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
2020-01-01,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
2020-01-02,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
2020-01-03,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
2020-01-04,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-07-01,0.733405,2.410542,0.780432,0.0,0.025137,0.0,0.000000,5.051286,14.031040,0.000000,...,0.000000,13.334755,0.115549,0.997522,1.059061,0.0,29.530026,0.102874,0.145568,0.116077
2020-07-02,0.838552,1.572092,0.847791,0.0,0.021995,0.0,0.000000,5.955694,17.682491,0.000000,...,7.649719,15.816940,0.202211,0.839859,0.806570,0.0,13.906582,0.109732,0.212754,0.095593
2020-07-03,0.488936,2.864702,0.894246,0.0,0.075412,0.0,2.059414,6.127643,20.049173,0.940645,...,5.737290,16.227497,0.115549,0.894435,0.739940,0.0,0.000000,0.106303,0.000000,0.081937
2020-07-04,0.793864,3.144185,0.959282,0.0,0.040848,0.0,0.000000,6.353187,22.382045,0.000000,...,12.430794,16.544456,0.144436,0.912627,0.925802,0.0,9.957800,0.065153,0.000000,0.054624
2020-07-05,0.914784,2.340671,0.998768,0.0,0.056559,0.0,0.000000,0.000000,19.609646,0.940645,...,0.000000,13.742273,0.086662,0.997522,0.746954,0.0,0.000000,0.027433,0.000000,0.498448

In [64]:
cases_14_days = cases.iloc[-28:,:]
cases_14_days

countriesAndTerritories,Afghanistan,Albania,Algeria,Andorra,Angola,Anguilla,Antigua_and_Barbuda,Argentina,Armenia,Aruba,...,United_States_Virgin_Islands,United_States_of_America,Uruguay,Uzbekistan,Venezuela,Vietnam,Western_Sahara,Yemen,Zambia,Zimbabwe
dateRep,,,,,,,,,,,,,,,,,,,,,
2020-06-08,2.079294,0.489095,0.241562,0.000000,0.015711,0.0,0.000000,1.728424,25.898257,0.000000,...,0.000000,6.777386,0.000000,0.518469,0.213916,0.002073,0.000000,0.044579,0.000000,0.020484
2020-06-09,1.511497,0.593902,0.257821,0.000000,0.003142,0.0,0.000000,1.844546,6.592898,0.000000,...,0.000000,5.719844,0.000000,0.291070,0.336655,0.001037,0.000000,0.034291,0.257544,0.034140
2020-06-10,1.424750,1.257674,0.271758,0.000000,0.012569,0.0,0.000000,2.547974,11.833407,0.000000,...,0.000000,5.672133,0.028887,0.300166,0.557585,0.000000,0.000000,0.096016,0.000000,0.184357
2020-06-11,1.798024,1.467286,0.236917,0.000000,0.053417,0.0,0.000000,2.766818,14.470567,0.000000,...,0.956215,6.264417,0.028887,0.448733,0.371723,0.000000,0.000000,0.123449,0.291137,0.040968
2020-06-12,1.963632,1.537157,0.243885,0.000000,0.015711,0.0,0.000000,3.066055,19.136310,0.000000,...,0.000000,6.953947,0.000000,0.375966,0.266519,0.000000,0.000000,0.106303,0.000000,0.081937
2020-06-13,1.724421,1.082997,0.253176,1.312732,0.037706,0.0,0.000000,3.106251,20.691558,0.000000,...,0.000000,7.791472,0.000000,0.248623,0.227944,0.001037,0.000000,0.140594,0.386316,0.075109
2020-06-14,1.461552,1.676899,0.260144,0.000000,0.025137,0.0,0.000000,3.418885,24.444438,0.000000,...,0.000000,7.761386,0.000000,0.281974,0.087671,0.001037,0.000000,0.250326,0.201556,0.088765
2020-06-15,1.745450,1.991317,0.253176,0.000000,0.006284,0.0,0.000000,2.862842,22.415854,0.000000,...,0.956215,5.938950,0.028887,0.330486,0.259505,0.000000,0.000000,0.078870,0.005599,0.184357
2020-06-16,2.000433,2.410542,0.260144,0.000000,0.006284,0.0,0.000000,2.697592,13.422465,0.000000,...,0.000000,6.064761,0.000000,0.576077,0.294573,0.000000,0.000000,0.397779,0.134371,0.027312
2020-06-17,2.058265,2.864702,0.269435,1.312732,0.000000,0.0,0.000000,3.068288,14.369137,0.000000,...,0.000000,7.203746,0.028887,0.812571,0.308601,0.001037,0.000000,0.154311,0.128772,0.047796
2020-06-18,1.482581,1.746769,0.281049,0.000000,0.040848,0.0,0.000000,3.110717,18.392496,0.000000,...,0.000000,7.767160,0.000000,0.412350,0.000000,0.000000,0.000000,0.044579,0.039191,0.047796
2020-06-19,1.729678,2.305736,0.271758,1.312732,0.000000,0.0,0.000000,0.000000,22.483474,0.000000,...,0.000000,8.436633,0.028887,0.479053,1.171279,0.007257,0.000000,0.013717,0.022395,0.423339
2020-06-20,0.909527,1.746769,0.276403,0.000000,0.034564,0.0,0.000000,8.972620,15.518668,0.000000,...,0.956215,9.089088,0.086662,0.515437,0.375230,0.007257,0.343372,0.044579,0.078383,0.109249
2020-06-21,1.435265,1.851576,0.294985,0.000000,0.018853,0.0,0.000000,3.648895,18.629164,0.000000,...,0.000000,10.380323,0.173324,0.579109,0.697858,0.000000,0.000000,0.013717,0.000000,0.047796
2020-06-22,1.075134,1.257674,0.325180,0.000000,0.012569,0.0,0.000000,3.530541,29.752567,0.000000,...,1.912430,7.838271,0.491084,0.430542,0.448874,0.000000,0.000000,0.061724,0.000000,0.020484
2020-06-23,0.814894,2.375606,0.346085,0.000000,0.021995,0.0,0.000000,4.792246,0.000000,0.000000,...,0.000000,9.539151,0.173324,0.430542,0.455887,0.000000,0.000000,0.089157,0.000000,0.157045
2020-06-24,0.888497,1.816640,0.362344,0.000000,0.009426,0.0,0.000000,0.000000,38.171191,0.000000,...,0.000000,10.551110,0.086662,0.773156,0.483942,0.000000,0.000000,0.085728,0.263143,0.088765
2020-06-25,0.615114,2.340671,0.399507,0.000000,0.009426,0.0,40.158575,10.986882,0.000000,0.000000,...,3.824860,10.435327,0.491084,0.712516,0.627722,0.003110,0.000000,0.078870,0.067185,0.034140
2020-06-26,1.209198,2.724960,0.457575,0.000000,0.025137,0.0,0.000000,5.819475,51.728895,0.000000,...,0.956215,12.444049,0.144436,0.721612,0.694351,0.000000,0.000000,0.209177,0.044790,0.143389
2020-06-27,0.725519,2.690025,0.557452,0.000000,0.047132,0.0,0.000000,0.000000,22.382045,0.000000,...,0.000000,13.835264,0.346647,0.794380,0.757474,0.001037,0.000000,0.044579,0.190359,0.068280
2020-06-28,0.433734,2.131059,0.657329,0.000000,0.100549,0.0,0.000000,11.806432,24.883965,0.000000,...,0.000000,12.911130,0.144436,0.712516,1.230895,0.001037,31.418574,0.048008,0.000000,0.040968
2020-06-29,0.922670,2.515348,0.708428,0.000000,0.072270,0.0,0.000000,0.000000,16.296292,0.000000,...,0.000000,11.752392,0.144436,0.927787,0.585640,0.001037,0.000000,0.051437,0.145568,0.000000
2020-06-30,0.712375,2.235865,0.692169,0.000000,0.028279,0.0,1.029707,10.102572,0.000000,1.881291,...,2.868645,12.628511,0.086662,0.809539,0.817090,0.000000,0.000000,0.034291,0.061587,0.047796
2020-07-01,0.733405,2.410542,0.780432,0.000000,0.025137,0.0,0.000000,5.051286,14.031040,0.000000,...,0.000000,13.334755,0.115549,0.997522,1.059061,0.000000,29.530026,0.102874,0.145568,0.116077
2020-07-02,0.838552,1.572092,0.847791,0.000000,0.021995,0.0,0.000000,5.955694,17.682491,0.000000,...,7.649719,15.816940,0.202211,0.839859,0.806570,0.000000,13.906582,0.109732,0.212754,0.095593
2020-07-03,0.488936,2.864702,0.894246,0.000000,0.075412,0.0,2.059414,6.127643,20.049173,0.940645,...,5.737290,16.227497,0.115549,0.894435,0.739940,0.000000,0.000000,0.106303,0.000000,0.081937
2020-07-04,0.793864,3.144185,0.959282,0.000000,0.040848,0.0,0.000000,6.353187,22.382045,0.000000,...,12.430794,16.544456,0.144436,0.912627,0.925802,0.000000,9.957800,0.065153,0.000000,0.054624
2020-07-05,0.914784,2.340671,0.998768,0.000000,0.056559,0.0,0.000000,0.000000,19.609646,0.940645,...,0.000000,13.742273,0.086662,0.997522,0.746954,0.000000,0.000000,0.027433,0.000000,0.498448

In [65]:
# 
cases_14_days_rolling_average = cases_14_days.rolling(window=14).mean().round(decimals=2)
cases_14_days_rolling_average

countriesAndTerritories,Afghanistan,Albania,Algeria,Andorra,Angola,Anguilla,Antigua_and_Barbuda,Argentina,Armenia,Aruba,...,United_States_Virgin_Islands,United_States_of_America,Uruguay,Uzbekistan,Venezuela,Vietnam,Western_Sahara,Yemen,Zambia,Zimbabwe
dateRep,,,,,,,,,,,,,,,,,,,,,
2020-06-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-06-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-06-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-06-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-06-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-06-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-06-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-06-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-06-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-06-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-06-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-06-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-06-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-06-21,1.67,1.64,0.26,0.28,0.02,0.0,0.00,3.06,17.74,0.00,...,0.20,7.27,0.03,0.44,0.37,0.0,0.02,0.11,0.11,0.10
2020-06-22,1.59,1.70,0.27,0.28,0.02,0.0,0.00,3.19,18.01,0.00,...,0.34,7.35,0.06,0.43,0.39,0.0,0.02,0.11,0.11,0.10
2020-06-23,1.54,1.83,0.27,0.28,0.02,0.0,0.00,3.40,17.54,0.00,...,0.34,7.62,0.08,0.44,0.39,0.0,0.02,0.12,0.09,0.11
2020-06-24,1.51,1.87,0.28,0.28,0.02,0.0,0.00,3.22,19.42,0.00,...,0.34,7.97,0.08,0.48,0.39,0.0,0.02,0.11,0.11,0.10
2020-06-25,1.42,1.93,0.29,0.28,0.02,0.0,2.87,3.80,18.39,0.00,...,0.55,8.27,0.11,0.50,0.41,0.0,0.02,0.11,0.09,0.10
2020-06-26,1.37,2.01,0.31,0.28,0.02,0.0,2.87,4.00,20.72,0.00,...,0.61,8.66,0.12,0.52,0.44,0.0,0.02,0.12,0.10,0.11
2020-06-27,1.30,2.13,0.33,0.19,0.02,0.0,2.87,3.78,20.84,0.00,...,0.61,9.09,0.15,0.56,0.48,0.0,0.02,0.11,0.08,0.11
2020-06-28,1.22,2.16,0.36,0.19,0.02,0.0,2.87,4.38,20.87,0.00,...,0.61,9.46,0.16,0.59,0.56,0.0,2.27,0.10,0.07,0.10
2020-06-29,1.16,2.20,0.39,0.19,0.03,0.0,2.87,4.17,20.43,0.00,...,0.55,9.87,0.17,0.63,0.58,0.0,2.27,0.10,0.08,0.09
2020-06-30,1.07,2.19,0.42,0.19,0.03,0.0,2.94,4.70,19.47,0.13,...,0.75,10.34,0.17,0.65,0.62,0.0,2.27,0.07,0.07,0.09
2020-07-01,0.98,2.15,0.46,0.09,0.03,0.0,2.94,4.84,19.45,0.13,...,0.75,10.78,0.18,0.66,0.67,0.0,4.38,0.07,0.08,0.10
2020-07-02,0.93,2.14,0.50,0.09,0.03,0.0,2.94,5.05,19.40,0.13,...,1.30,11.36,0.19,0.69,0.73,0.0,5.37,0.07,0.09,0.10
2020-07-03,0.84,2.18,0.54,0.00,0.04,0.0,3.09,5.49,19.22,0.20,...,1.71,11.91,0.20,0.72,0.70,0.0,5.37,0.08,0.09,0.08
2020-07-04,0.83,2.28,0.59,0.00,0.04,0.0,3.09,5.30,19.71,0.20,...,2.53,12.45,0.20,0.75,0.74,0.0,6.06,0.08,0.08,0.07
2020-07-05,0.80,2.32,0.64,0.00,0.04,0.0,3.09,5.04,19.78,0.27,...,2.53,12.69,0.20,0.78,0.74,0.0,6.06,0.08,0.08,0.10